# preprocess
MAX_LENGTH = 49
WORD_COUNT_THRESHOLD = 5
NUM_OBJECT = 20

# model
PAD_IDX = 0

MODEL_NAME = 'maxlen49_20obj'
OUTPUT_NAME = 'maxlen49_20obj'
DATA_PATH = f'./data/{MODEL_NAME}'
OUTPUT_PATH = f'./output/{OUTPUT_NAME}'
WORD_TO_IDX_PATH = f'{DATA_PATH}/train/word_index.pkl'

# encoder
ENCODE_DIM_FEATURES = 2048
ENCODE_DIM_POSITIONS = 84

ENCODE_INPUT_SIZE = 16
ENCODE_Q_K_DIM = 32
ENCODE_V_DIM = 32
ENCODE_HIDDEN_SIZE = 32
ENCODE_NUM_BLOCKS = 1
ENCODE_NUM_HEADS = 4

# decoder
DIM_WORD_EMBEDDING = 16

DECODE_INPUT_SIZE = 16
DECODE_Q_K_DIM = 32
DECODE_V_DIM = 32
DECODE_HIDDEN_SIZE = 32
DECODE_NUM_BLOCKS = 2
DECODE_NUM_HEADS = 4

DROPOUT = 0.2

# solver
NUM_EPOCH = 500
BATCH_SIZE = 64
LEARNING_RATE = 0.001
LOG_PATH = f'./logs_{OUTPUT_NAME}/'

# # 64
# # encoder
# ENCODE_INPUT_SIZE = 64
# ENCODE_Q_K_DIM = 64
# ENCODE_V_DIM = 64
# ENCODE_HIDDEN_SIZE = 64
# ENCODE_NUM_BLOCKS = 2
# ENCODE_NUM_HEADS = 2

# # decoder
# DIM_WORD_EMBEDDING = 64

# DECODE_INPUT_SIZE = 64
# DECODE_Q_K_DIM = 64
# DECODE_V_DIM = 64
# DECODE_HIDDEN_SIZE = 64
# DECODE_NUM_BLOCKS = 4
# DECODE_NUM_HEADS = 2

# # 128
# # encoder
# ENCODE_INPUT_SIZE = 64
# ENCODE_Q_K_DIM = 128
# ENCODE_V_DIM = 128
# ENCODE_HIDDEN_SIZE = 128
# ENCODE_NUM_BLOCKS = 2
# ENCODE_NUM_HEADS = 4

# # decoder
# DIM_WORD_EMBEDDING = 128

# DECODE_INPUT_SIZE = 64
# DECODE_Q_K_DIM = 128
# DECODE_V_DIM = 128
# DECODE_HIDDEN_SIZE = 128
# DECODE_NUM_BLOCKS = 4
# DECODE_NUM_HEADS = 4

# # 128_14b
# # encoder
# ENCODE_INPUT_SIZE = 128
# ENCODE_Q_K_DIM = 128
# ENCODE_V_DIM = 128
# ENCODE_HIDDEN_SIZE = 128
# ENCODE_NUM_BLOCKS = 1
# ENCODE_NUM_HEADS = 4

# # decoder
# DIM_WORD_EMBEDDING = 128

# DECODE_INPUT_SIZE = 128
# DECODE_Q_K_DIM = 128
# DECODE_V_DIM = 128
# DECODE_HIDDEN_SIZE = 128
# DECODE_NUM_BLOCKS = 4
# DECODE_NUM_HEADS = 4

# # 256_13b
# # encoder
# ENCODE_INPUT_SIZE = 128
# ENCODE_Q_K_DIM = 256
# ENCODE_V_DIM = 256
# ENCODE_HIDDEN_SIZE = 128
# ENCODE_NUM_BLOCKS = 1
# ENCODE_NUM_HEADS = 4

# # decoder
# DIM_WORD_EMBEDDING = 128

# DECODE_INPUT_SIZE = 128
# DECODE_Q_K_DIM = 256
# DECODE_V_DIM = 256
# DECODE_HIDDEN_SIZE = 128
# DECODE_NUM_BLOCKS = 3
# DECODE_NUM_HEADS = 4

# # 128_14b_8h
# # encoder
# ENCODE_INPUT_SIZE = 128
# ENCODE_Q_K_DIM = 128
# ENCODE_V_DIM = 128
# ENCODE_HIDDEN_SIZE = 256
# ENCODE_NUM_BLOCKS = 1
# ENCODE_NUM_HEADS = 8

# # decoder
# DIM_WORD_EMBEDDING = 256

# DECODE_INPUT_SIZE = 128
# DECODE_Q_K_DIM = 128
# DECODE_V_DIM = 128
# DECODE_HIDDEN_SIZE = 256
# DECODE_NUM_BLOCKS = 4
# DECODE_NUM_HEADS = 8

# # 128_14b_16h
# # encoder
# ENCODE_INPUT_SIZE = 128
# ENCODE_Q_K_DIM = 128
# ENCODE_V_DIM = 128
# ENCODE_HIDDEN_SIZE = 256
# ENCODE_NUM_BLOCKS = 1
# ENCODE_NUM_HEADS = 16

# # decoder
# DIM_WORD_EMBEDDING = 256

# DECODE_INPUT_SIZE = 128
# DECODE_Q_K_DIM = 128
# DECODE_V_DIM = 128
# DECODE_HIDDEN_SIZE = 256
# DECODE_NUM_BLOCKS = 4
# DECODE_NUM_HEADS = 16
